name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install

      - run: pnpm build

      - name: Publish core package
        if: startsWith(github.event.release.tag_name, 'core@')
        run: pnpm --filter obsidian-minimum-required-version publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish eslint-plugin
        if: startsWith(github.event.release.tag_name, 'eslint-plugin@')
        run: pnpm --filter eslint-plugin-obsidian-minimum-required-version publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
